### ISSUE TITLE
are deployments working?

### ISSUE THREAD

**Issue by glyph** [tweedge/unique-local-ipv6#4]
I see https://github.com/tweedge/unique-local-ipv6/actions/runs/8485392451/job/23250077670 ran successfully, but I don't see #3 live on https://unique-local-ipv6.com so I am wondering if there's a BunnyCDN configuration issue.

**Comment by tweedge** [comment]
Whoop, good catch. The cache settings are quite aggressive as updates are infrequent :sweat_smile: 

I've purged it manually now - how's it look on your end?

**Comment by glyph** [comment]
Cache headers client-side must be a bit aggressive still, because I had to manually check "disable caches" in the network view in Safari to get it to be monospaced, but it's definitely being served now. Thanks!
